=== uo251950/sew/practica2/Ejercicio-1/Tarea-2/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (tipo, dificultad, tiempo, agencia, descripcion, aptos, lugar_inicio, direccion_inicio, coordenadas, referencias, hitos)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT dificultad (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT aptos (#PCDATA)>
<!ELEMENT lugar_inicio (#PCDATA)>
<!ELEMENT direccion_inicio (#PCDATA)>
<!ELEMENT coordenadas (latitud, longitud, altitud)>
<!ELEMENT latitud (grados, minutos, segundos)>
<!ELEMENT grados (#PCDATA)>
<!ELEMENT minutos (#PCDATA)>
<!ELEMENT segundos (#PCDATA)>
<!ELEMENT longitud (grados, minutos, segundos)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre, descripcion, coordenadas, distancia_predecesor, imagenes)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT distancia_predecesor (#PCDATA)>
<!ELEMENT imagenes (imagen+)>
<!ELEMENT imagen (#PCDATA)>

<!ATTLIST ruta 
	nombre CDATA #REQUIRED
	recomendacion CDATA #REQUIRED>
<!ATTLIST latitud 
	var CDATA #REQUIRED>
<!ATTLIST longitud 
	var CDATA #REQUIRED>
<!ATTLIST altitud 
	unidades CDATA #REQUIRED>
<!ATTLIST referencia 
	tipo CDATA #REQUIRED>
<!ATTLIST distancia_predecesor 
	unidades CDATA #REQUIRED>
<!ATTLIST imagen 
	tipo CDATA #REQUIRED>

=== uo251950/sew/practica2/Ejercicio-1/Tarea-1/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">

<rutas>
    <ruta nombre="Caminito del Rey" recomendacion="10">
        <tipo>Ruta por desfiladero</tipo>
        <dificultad>Solo para expertos</dificultad>
        <tiempo>4 horas</tiempo>
        <agencia>Sin agencia</agencia>
        <descripcion>
            El Caminito del Rey es un paso construido en las paredes del desfiladero de los Gaitanes, entre los términos municipales de Ardales, 
            Álora y Antequera, en la provincia de Málaga, comunidad autónoma de Andalucía, España. Se trata de una pasarela peatonal de más de tres 
            kilómetros (además de 4,8 kilómetros de accesos), adosada a la roca en el interior de un cañón, con tramos de una anchura de apenas un metro, 
            colgando hasta 105 metros de altura sobre el río, en unas paredes casi verticales.
        </descripcion>
        <aptos>Únicamente adultos en buen estado de forma</aptos>
        <lugar_inicio>Desfiladero de los Gaitanes</lugar_inicio>
        <direccion_inicio>El Caminito del Rey, 29550, Málaga</direccion_inicio>
        <coordenadas>
			<latitud var="N">
				<grados>36</grados>
				<minutos>54</minutos>
				<segundos>57</segundos>
			</latitud>
			<longitud var="O">
				<grados>4</grados>
				<minutos>46</minutos>
				<segundos>22</segundos>
			</longitud>
			<altitud unidades="m">105</altitud>
        </coordenadas>
        <referencias>
			<referencia tipo="url">...</referencia>
			<referencia tipo="url">...</referencia>
			<referencia tipo="url">...</referencia>
		</referencias>
        <hitos>
            <hito>
                <nombre></nombre>
				<descripcion></descripcion>
				<coordenadas>
					<latitud var="">
						<grados></grados>
						<minutos></minutos>
						<segundos></segundos>
					</latitud>
					<longitud var="">
						<grados></grados>
						<minutos></minutos>
						<segundos></segundos>
					</longitud>
					<altitud unidades="m"></altitud>
				</coordenadas>
				<distancia_predecesor unidades="km"></distancia_predecesor>
				<imagenes>
					<imagen tipo="ruta_local"></imagen>
					<imagen tipo="ruta_local"></imagen>
					<imagen tipo="ruta_local"></imagen>
				</imagenes>
				<videos>
					<video tipo="url"></video>
				</videos>    
            </hito>
        </hitos>
    </ruta>
</rutas>
